name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}
    strategy:
      matrix:
        php: [8.0, 7.4, 7.3]
        laravel: [8.*, 7.*, 6.*]
        dependency-version: [prefer-lowest, prefer-stable]
        include:
              - laravel: 8.*
                testbench: ^6.3
              - laravel: 7.*
                testbench: ^5.8
              - laravel: 6.*
                testbench: ^4.9
    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate
   
    - name: Install dependencies
      run: |
            composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-suggest --no-interaction --no-update
            composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

    - name: Run test suite
      run: composer test
